version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 16
      - npm i yarn -g
  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - aws s3 rm s3://pranesh-react-app --recursive
      - aws s3 sync ./build s3://pranesh-react-app --acl public-read
