name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      # - name: Run the tests
      #   run: npm test
      - name: Build
        run: npm run build
