name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install yarn
        run: npm i yarn -g
      - name: Install dependencies
        run: yarn
      # - name: Run the tests
      #   run: npm test
      - name: Build
        run: CI="" yarn build
