name: PR

on:
  pull_request:
    branches: [master]

jobs:
  pull_request:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Install yarn
        run: npm i yarn -g
      - name: Install dependencies
        run: yarn
      # - name: Run the tests
      #   run: npm test
      - name: Build
        run: yarn build
